### ISSUE TITLE
Invalid params error when recording from GUI

### ISSUE THREAD

**Issue by bennlich** [foss-project/green-recorder#113]
I'm occasionally seeing this error in syslog when I click the record button in the GUI. It seems to depend on what size area I am trying to record.

```
Dec 21 19:58:13 secret-susan green-recorder.desktop[1472]: Traceback (most recent call last):
Dec 21 19:58:13 secret-susan green-recorder.desktop[1472]:   File "/usr/bin/green-recorder", line 417, in recordclicked
Dec 21 19:58:13 secret-susan green-recorder.desktop[1472]:     record()
Dec 21 19:58:13 secret-susan green-recorder.desktop[1472]:   File "/usr/bin/green-recorder", line 239, in record
Dec 21 19:58:13 secret-susan green-recorder.desktop[1472]:     RecordGnome()
Dec 21 19:58:13 secret-susan green-recorder.desktop[1472]:   File "/usr/bin/green-recorder", line 180, in RecordGnome
Dec 21 19:58:13 secret-susan green-recorder.desktop[1472]:     GNOMEScreencast.ScreencastArea(WindowXAxis, WindowYAxis, WindowWidth, WindowHeight, RecorderAbsPathName, {'framerate': GLib.Variant('i', int(RecorderFrames)), 'draw-cursor': GLib.Variant('b', mousecheck.get_active()), 'pipeline': GLib.Variant('s', RecorderPipeline)})
Dec 21 19:58:13 secret-susan green-recorder.desktop[1472]:   File "/usr/lib/python2.7/dist-packages/pydbus/proxy_method.py", line 75, in __call__
Dec 21 19:58:13 secret-susan green-recorder.desktop[1472]:     0, timeout_to_glib(timeout), None).unpack()
Dec 21 19:58:13 secret-susan green-recorder.desktop[1472]: gi.repository.GLib.Error: g-io-error-quark: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code19: Invalid params (19)
```

I'm using wayland on debian.

**Comment by bennlich** [comment]
Hmm. After an apt upgrade, I'm not seeing this error anymore. I'll re-open if it comes back.
