### ISSUE TITLE
The app isn't starting on Wayland

### ISSUE THREAD

**Issue by notuxius** [foss-project/green-recorder#92]
error displayed on start:
~ % green-recorder 
You are recording on: wayland
Traceback (most recent call last):
  File "/usr/bin/green-recorder", line 80, in <module>
    GNOMEScreencast = bus.get('org.gnome.Shell.Screencast', '/org/gnome/Shell/Screencast')
  File "/usr/lib/python2.7/site-packages/pydbus/proxy.py", line 47, in get
    0, timeout_to_glib(timeout), None)
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Shell.Screencast was not provided by any .service files (2)

package installed from AUR:
https://aur.archlinux.org/packages/green-recorder/

info about system:
Plasma: 5.12.4
Apps: 17.12.3
Frameworks: 5.45.0
Qt: 5.10.1
Kernel: 4.14.34-1-MANJARO
OS: Netrunner Rolling
Video: Intel 4400
Driver: xf86-video-intel 1:2.99.917+823+gd9bf46e4-1
Screen: 1600x900
wayland-protocols 1.13-1
wayland 1.14.0-1

**Comment by mhsabbagh** [comment]
Recording on KDE Plasma (Wayland backend) is not supported.

**Comment by JonasT** [comment]
@mhsabbagh wouldn't it be smarter to get KDE & GNOME to make a unified wayland API? doesn't seem healthy in the long run if everyone makes their own different screencasting API

**Comment by keithbowes** [comment]
> @mhsabbagh wouldn't it be smarter to get KDE & GNOME to make a unified wayland API? doesn't seem healthy in the long run if everyone makes their own different screencasting API

https://gitlab.freedesktop.org/wayland/wayland/issues/32

Of course, if this ever happens, it probably won't resemble the GNOME API (as GNOME is notorious for not going along with what other compositors decide).
